{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chatty.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chatty.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.tls.enabled }}
  tls:
  - secretName: {{ .Values.DOMAIN }}-tls
    hosts:
      - {{ .Values.DOMAIN }}
  {{- end }}
  rules:
    - host: {{ .Values.DOMAIN }}
      http:
        paths:
        - path: {{ .Values.ingress.path }}
          pathType: {{ .Values.ingress.pathType | default "Prefix" }}
          backend:
            service:
              name: {{ include "chatty.fullname" . }}
              port:
                number: {{ .Values.service.port }}
{{- end }}
