name: CD Pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

env:
  IMAGE_REPOSITORY: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ github.sha }}
  NAMESPACE: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_REPOSITORY:$IMAGE_TAG .
          docker push $IMAGE_REPOSITORY:$IMAGE_TAG

      - name: Deploy with Helm
        uses: ./.github/actions/helm-deploy
        with:
          image_tag: ${{ env.IMAGE_TAG }}
          registry_repository: ${{ env.IMAGE_REPOSITORY }}
          kube_config_data: ${{ secrets.KUBE_CONFIG_DATA }}
          chatty_env: ${{ secrets.CHATTY_ENV }}
          namespace: ${{ env.NAMESPACE }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
